- autoload/fuzzy/ag.vim
job_start() parses passed in command-line for parameters escaped with double quotes, so escape it in parameters when formatting external command.
Path is also affected and needs escaping.
> Fix grepping for patterns containing "

- autoload/fuzzy/inbuffer.vim
This was reporting that `1` was not a valid key on the dictionary, and
digging through the calls indicated that the correct option is now
`.prompt`.
> Fix fuzzy#inbuffer.Start

- autoload/fuzzy/ag.vim
- autoload/fuzzy/files.vim
- autoload/fuzzy/mru.vim
When vim-sleuth plugin is used, selecting a file to edit from fuzzyy results in error E930: Cannot use :redir inside execute(), e.g.
Error detected while processing function <SNR>153_MenuFilter[28]..<SNR>153_GeneralPopupCallback[17]..<SNR>61_Select[5]..BufRead Autocommands for "*"..function <SNR>115_AutoInit[1]..<SNR>115_Init[15]..<SNR
>115_DetectDeclared[21]..<SNR>115_ModelineOptions[2]..<SNR>115_Capture:
line    1:
E930: Cannot use :redir inside execute()
Error detected while processing function <SNR>153_MenuFilter[28]..<SNR>153_GeneralPopupCallback[17]..<SNR>61_Select[5]..BufRead Autocommands for "*"..function <SNR>115_AutoInit[1]..<SNR>115_Init[15]..<SNR
>115_DetectDeclared:
line   21:
E712: Argument of extend() must be a List or Dictionary
Fix using `:execute` rather than …
> Fix incompatibility with vim-sleuth

- autoload/fuzzyy/utils/selector.vim
Move the code to show the warning to after the popups have been created,
which avoids the "Press ENTER or type command to continue" prompt when
the width of the message is wider than the current window (by the time
the message is echoed the current window is the fuzzyy prompt window)
But retain then use of echow for warnings re deprecated commands. These
warnings should only be shown when running the deprecated command, not
included in the shared list of deprecations for configuration options,
but we still need to avoid "Press ENTER or type command to continue".
We could pass the relevant warning(s) to selector.Start() and only show
one message, but that seems an overly complex solution to this problem,
and the combination of echow and echo actually works quite nicely.
> better deprecation warnings

- README.md
- autoload/fuzzyy/files.vim
- autoload/fuzzyy/mru.vim
- autoload/fuzzyy/utils/selector.vim
- plugin/fuzzyy.vim
This adds variants of FuzzyGrep, FuzzyFiles, and FuzzyMru commands to search within the "project" root, initially by simply looking for known source control root markers in the filesystem, but could be extended with other checks.
The default root patterns are intentionally conservative, not including patterns specific to build and packaging tools, programming languages, editors etc. as it's very difficult to set defaults including these things that are both widely applicable and will stand the test of time. Some code repositories also contain multiple packages, so even defining what is a project is not always obvious, probably best left to users.
A possibly unobvious, but positive, side-effect of these changes is that they make it possible to pass an arbitrary `cwd` option to any of the …
> Add FuzzyGrepRoot, FuzzyFilesRoot, and FuzzyMruRoot commands

- README.md
- plugin/fuzzyy.vim
Avoids breaking any custom configuration in a user's vimrc when adding
the fuzzyy leader mappings (also allows users to remap fuzzyy mappings)
> Do not overwrite any existing leader mappings

- README.md
- autoload/fuzzyy/tags.vim
- autoload/fuzzyy/utils/selector.vim
- plugin/fuzzyy.vim
Tested with JS, Python, Ruby, C, and Markdown, should work fine with
other languages assuming tag address locates the correct line in file.
Only tested with Universal ctags, https://ctags.io/, may not support tag
files generated by other tag programs (can be addressed later if needed)
Supports CTRL+{s,t,v} keymaps to open in splits and tab, like FuzzyFiles etc.
Screenshot in use within fuzzy codebase... 
Also tested with much larger codebases, including a mostly js codebase I work with regularly which has 190,863 tags.
> Add FuzzyTags and FuzzyTagsRoot commands

- autoload/fuzzyy/files.vim
- autoload/fuzzyy/grep.vim
- autoload/fuzzyy/mru.vim
- autoload/fuzzyy/tags.vim
- autoload/fuzzyy/utils/selector.vim
Check modelines when filetype not detected using filetypedetect autocmd
Fuzzyy disables modelines for the preview window, which is sensible, you
don't want a modeline setting options and messing up the preview window.
But, this does mean that syntax highlighting is not enabled for some
files in the preview, but is enabled when opening the file for editing.
To address this, parse modelines if 'modeline' is on or securemodelines
plugin has been loaded (this is an old, but widely referenced plugin).
Note the check for either an empty &filetype or &filetype == 'conf'.
This is because 'conf' is used as the FALLBACK filetype in filetype.vim,
see :h :setfiletype and $VIMRUNTIME/filetype.vim, search for FALLBACK.
Note: Telescope.nvim also parse modelines, LeaderF just sets 'modeline'
> WIP: Add modeline fallback to detect preview filetype

- README.md
- autoload/fuzzyy/inbuffer.vim
- autoload/fuzzyy/utils/selector.vim
Works more or less the same as Telescope.nvim, but no option yet to
select multiple results, just sends all visible results to quickfix.
LeaderF has a similar feature, but with a different mapping, fzf.vim
also has a similar feature, but you need to select multiple results
first (Telescope also allows this, but by default sends all to qf).
> Add CTRL-Q keymap to send results to quickfix list

- README.md
- autoload/fuzzyy/utils/devicons.vim
- doc/fuzzyy.txt
This allows other plugins or custom functions to be used for devicons,
e.g. for vim-nerdfont `let g:fuzzyy_devicon_func = 'nerdfont#find'`
Note: vim-nerdfont does not follow the typical pattern for vim plugins
to set a "g:plugin_loaded" variable, and only uses autoloaded functions,
so there is no easy way for fuzzyy to check if it has been loaded.
Technical note: Fuzzyy measures the byte width for a single glyph and
assumes all glyphs returned by the devicon function are the same width
(this is almost certainly true, they should all be in the same Unicode
private use area so should use the same number of bytes in utf8, but
if you run into some weirdness with a custom function, could be this)
> Allow devicons to be customised (use other nerdfont compatible plugins for glyphs and colors)

- autoload/fuzzyy/utils/popup.vim
When the content of the prompt changes, and triggers the input callback,
reset the menu cursor position as this normally changes the content and
the cursor should be re-positioned on the first/best match after the
results change. This now works the same as Telescope.nvim and LeaderF.
> Reset menu cursor position on input to prompt

- autoload/fuzzyy/utils/devicons.vim
- autoload/fuzzyy/utils/popup.vim
Some features require utf-8, i.e. devicons and custom borderchars. 
Fuzzyy starts with a warning when the encoding is not utf-8, but even
better to show the warning and disable the features that require utf-8.
**before**
**after**
> Disable utf-8 features when &encoding not utf-8

- README.md
- autoload/fuzzyy/utils/colors.vim
- autoload/fuzzyy/utils/devicons.vim
- compat/fuzzyy.vim
- doc/fuzzyy.txt
- plugin/fuzzyy.vim
This adds a new compat script loaded on VimEnter where compatibilities with other plugins can be defined, moves the existing vim-devicons compatibility code to that compat script, and adds similar code for vim-nerdfont, vim-glyph-palette, and vim-nerdtree-syntax-highlight. 
vim-devicons remains the first priority for the devicons glyph function, vim-glyph-palette and vim-nerdtree-syntax-highlight will only be used automatically if the user has not already set g:fuzzyy_devicons_color_func. For an existing user of nerdtree, vim-nerdtree-syntax-highlight, and fuzzyy, they will now magically get the same colors in Fuzzyy as in  NERDTree (for all devicons known to Fuzzyy)
**before**
**after** (with vim-nerdtree-syntax-highlight) 
**after** (with vim-glyph-palette)
**after** (with vim-nerdfont, …
> Add vim-nerdfont, vim-glyph-palette, and vim-nerdtree-syntax-highlight compatibility

- autoload/fuzzyy/grep.vim
Example that failed previously:
git version 2.39.5 (Apple Git-154)
> Correct how git version is parsed

- autoload/fuzzyy/utils/popup.vim
The previous code to resolve the cursor highlight didn't allow for only
the background or foreground to be set, i.e. only one of guifg & guibg.
This was done intentionally to keep the code simple, on the assumption
that only setting either background or foreground was so rare that it
didn't warrant the additional complexity, but it seems that assumption
was misguided, while it is unusual, it's not rare enough to ignore.
See https://github.com/Donaldttt/fuzzyy/pull/84 for background
Thanks @casr for reporting this and researching in some detail :-)
> Handle only bg or fg set when resolving cursor hl

- README.md
- autoload/fuzzyy/utils/popup.vim
- doc/fuzzyy.txt
When using vim-lsp, language servers are started automatically when the
filetype is changed, which happens within the Fuzzyy preview window.
Adding user autocmds that are triggered when Fuzzyy opens and closes
allows vim-lsp to be disabled temporarily while Fuzzyy is open, e.g.
augroup LspFuzzyy
autocmd!
autocmd User FuzzyyOpened call lsp#disable()
autocmd User FuzzyyClosed call lsp#enable()
augroup END
It turns out that setting `let g:lsp_untitled_buffer_enabled = 0`
achieves the same thing, but that is not exactly obvious from the
variable name (only looking at the code is it clear what this does).
Having said that, adding these user autocmds seems a good thing to allow
for compatibility with other plugins in general, not just for vim-lsp.
Note: this change replaces the PopupClosed user …
> Add user autocmds to aid plugin compatibility

- autoload/fuzzyy/utils/popup.vim
- plugin/fuzzyy.vim
Similar to telescope.nvim, somewhat experimental, may also warrant
adding a global config option to disable prompt titles, not sure.
Personally I find this very helpful, especially when resuming a
previously loaded selector (see other PR that adds this feature).
Defaults are English only at the moment, but can easily be customised.
> Add option to set prompt title and set defaults

- README.md
- autoload/fuzzyy/utils/launcher.vim
- autoload/fuzzyy/utils/popup.vim
- doc/fuzzyy.txt
- plugin/fuzzyy.vim
This adds a feature similar to those found in Telescope, LeaderF and FZF.vim to allow the previous selector and search to be reloaded.
The new launcher script is used to start selectors, and caches previous launches, allowing the most recent one which also has some saved input to be resumed. The cache currently only stores one previous launch (the last one that had some associated input and can therefore be resumed).
This could be extended later to allow resumption of specific selectors, but just using the previous one with an some input is a good start.
I'm also thinking of this new launcher script as a general entry point for launching selectors, allowing extensions to register selectors in future (something along the lines of how Telescope extensions work).
Note: some minor changes …
> Add FuzzyyPrevious command, reload previous search

- autoload/fuzzyy/buffers.vim
- autoload/fuzzyy/files.vim
- autoload/fuzzyy/grep.vim
- autoload/fuzzyy/mru.vim
- autoload/fuzzyy/utils/popup.vim
- autoload/fuzzyy/utils/selector.vim
Move more of the code for handling devicons into core files so most
selectors don't need to worry about the details, set `devicons: true`
in opts to selector.Start() and it just works; devicons are added to
the results in the menu, and then removed from selected items passed
to preview, select and close callbacks.
Some custom handling remains within the files and grep selectors as they
currently require custom code to parse results when updating the menu.
Will revisit another time and see if I can remove the need for this.
> Simplify devicons handling for most selectors

- autoload/fuzzyy/builtin/buffers.vim
- autoload/fuzzyy/builtin/colors.vim
- autoload/fuzzyy/builtin/files.vim
- autoload/fuzzyy/builtin/grep.vim
- autoload/fuzzyy/builtin/help.vim
- autoload/fuzzyy/builtin/highlights.vim
- autoload/fuzzyy/builtin/inbuffer.vim
- autoload/fuzzyy/builtin/mru.vim
- autoload/fuzzyy/builtin/tags.vim
- autoload/fuzzyy/utils/popup.vim
- autoload/fuzzyy/utils/selector.vim
Adding PR for visibility. The aim here is to simplify the callbacks to make them easier to use.
* Consistent internal names (i.e. remaining references to `move_cb` changed to `select_cb`)
* Clearly separate the responsibilities of close and select callbacks (use close only for cleanup)
* Remove redundant code to create a list of close funcs, this was only used for `select_cb`
* Send relevant window id as first arg to callback, not menu window id (esp. useful for preview callback)
* Send results/selection as separate arg to relevant callbacks (no need to delve into opts dict)
* Remove opts dict from function signatures and when invoking callback functions (not needed anymore)
> Simplify callbacks

- autoload/fuzzbox/builtin/buffers.vim
- autoload/fuzzbox/builtin/files.vim
- autoload/fuzzbox/builtin/grep.vim
- autoload/fuzzbox/builtin/highlights.vim
- autoload/fuzzbox/builtin/inbuffer.vim
- autoload/fuzzbox/builtin/mru.vim
- autoload/fuzzbox/builtin/tags.vim
- autoload/fuzzbox/utils/actions.vim
- autoload/fuzzbox/utils/popup.vim
- autoload/fuzzbox/utils/selector.vim
Add PR for visibility.
Actions can be used to associate behaviour with keymaps. The difference
with key_callbacks is that they are invoked with pre-defined arguments,
the menu wid, the selected results, and opts used when creating popups.
The arguments allow the functions to be shared as they no longer rely
on script or global scope vars to execute commands in the window, access
the selected results, or obtain knowledge of the initialisation context
(e.g. to check the working directory or whether devicons are enabled).
Related to: https://github.com/Donaldttt/fuzzyy/issues/104
Based on `fuzzbox` branch, not planning to merge until repo moved
> Replace key callbacks with "actions"

- LICENSE
As discussed on https://github.com/vim-fuzzbox/fuzzbox.vim/issues/99
Transferring copyright from Nachuan Tang to vim-fuzzbox organization
> Change copyright owner in LICENSE to vim-fuzzbox
